Feature/6 privacy policy
WPU-APCS-370/ahcer-episode-recorder pull request #20
Opened 2022-05-27 01:24 UTC by carlyspikes

privacy policy page

2022-05-27 19:01 UTC, KaungHT13 requested changes
There were some duplicates. Also, the main website that the users will access will be [https://ahcer.org/](https://ahcer.org/) instead of [https://ahcer.azurewebsites.net/](https://ahcer.azurewebsites.net/), and login route should not be provided for the privacy policy. Apart from those, looks good to me.

2022-05-27 20:13 UTC, runrobrun commented on ahcer/src/app/privacy-policy/privacy-policy.component.html
> +<p>At e-AHC, accessible from https://ahcer.azurewebsites.net/login, one of our main priorities is the privacy of our visitors. This Privacy Policy document contains types of information that is colle
I would stick with capital E

2022-05-27 20:14 UTC, runrobrun commented on ahcer/src/index.html
> +<body class="mat-typography">
ensures that the site consistently uses same fonts, sizes etc.

2022-06-01 03:53 UTC, chimezieokeke commented
In terms of the privacy policy, I checked out your branch and it looks good!

2022-06-01 03:55 UTC, chimezieokeke reviewed
Looks good!

2022-06-01 04:36 UTC, KaungHT13 commented on ahcer/src/app/privacy-policy/privacy-policy.component.html
> +<p>At E-AHC, accessible from https://ahcer.org/, one of our main priorities is the privacy of our visitors. This Privacy Policy document contains types of information that is collected and recorded b
You missed an e-AHC near the end of this line. Also, the same thing at line 8.

2022-06-01 04:37 UTC, KaungHT13 commented on ahcer/src/app/privacy-policy/privacy-policy.component.html
> +<p>Third-party ad servers or ad networks uses technologies like cookies, JavaScript, or Web Beacons that are used in their respective advertisements and links that appear on EF-AHC, which are sent di
There is an extra F. Should be E-AHC instead of EF-AHC.

2022-06-01 04:45 UTC, KaungHT13 approved these changes
Looks good!

2022-06-01 04:47 UTC, merged